"""Services package."""

from services.bookings import (
    BookingError,
    BookingNotFoundError,
    ConflictError,
    create_booking,
    get_active_booking,
    get_booking,
    get_user_bookings,
    list_bookings,
)
from services.scheduler import SchedulerManager, get_scheduler_manager
from services.voting import (
    VotingError,
    VotingNotFoundError,
    VotingPermissionError,
    VotingStateError,
    add_fire_reaction,
    cancel_session,
    cast_final_vote,
    check_min_votes,
    create_vote_session,
    end_suggest,
    end_vote,
    get_active_session_for_chat,
    get_final_vote_counts,
    get_vote_session,
    get_winner,
    list_movies,
    remove_fire_reaction,
    retry_vote,
    run_filter_stage,
    select_winner,
    suggest_movie,
    transition_state,
)

__all__ = [
    # bookings
    "BookingError",
    "BookingNotFoundError",
    "ConflictError",
    "create_booking",
    "get_active_booking",
    "get_booking",
    "get_user_bookings",
    "list_bookings",
    # scheduler
    "SchedulerManager",
    "get_scheduler_manager",
    # voting
    "VotingError",
    "VotingNotFoundError",
    "VotingPermissionError",
    "VotingStateError",
    "add_fire_reaction",
    "cancel_session",
    "cast_final_vote",
    "check_min_votes",
    "create_vote_session",
    "end_suggest",
    "end_vote",
    "get_active_session_for_chat",
    "get_final_vote_counts",
    "get_vote_session",
    "get_winner",
    "list_movies",
    "remove_fire_reaction",
    "retry_vote",
    "run_filter_stage",
    "select_winner",
    "suggest_movie",
    "transition_state",
]